--- # Poggit-CI Manifest. Open the CI at https://poggit.pmmp.io/ci/drirainMCBE/translator
build-by-default: true
branches:
- master
projects:
  translator:
    path: ""
    model: virion
    type: library
...
