--- # Poggit-CI Manifest. Open the CI at https://poggit.pmmp.io/ci/drirainMCBE/translater
build-by-default: true
branches:
- master
projects:
  translater:
    path: ""
    model: virion
    type: library
...
